### PR TITLE
test stability changes

### LINKED ISSUE #451: selinux issues while running tests
Looking at ffi packet test results i see too many  errors like this one 
```
Relabeled /var/lib/containers/storage/overlay-containers/da316b1062ee5dce9044b6bde054801891601d2e770f700dcfa1c08e2a5c75d5 from unconfined_u:object_r:container_var_lib_t:s0 to system_u:object_r:container_var_lib_t:s0
```

please see this output 
https://artifacts.dev.testing-farm.io/0f693132-db2f-43af-8363-e6d3196c1b73/work-ffikrs_25fp/plans/e2e/ffi/execute/data/guest/default-0/tests/ffi/qm-oom-score-adj-3/output.txt

Verify images are removed 
as per this 
```
   Now, if you remove a container from the container runtime and leave the content on disk,
  there is a chance the label will be reused. The best thing to do with this content is to  
  change the type of the content when the container is removed. The command 
  restorecon -rF /var/lib/previouscontainer will force the label of the content back to a 
  label that containers can't read/write.

```

### LINKED ISSUE #462: CI/CD e2e-tier-0 tests failures in bluechi-controller
Tiers e2e tests started to fail on qm-node

Jun 14 15:48:57 control bluechi-controller[158]: Node 'qm-node1' disconnected
Jun 14 15:49:53 control bluechi-controller[158]: Registered managed node from fd 11 as 'qm-node1'

While bluechi-agent inside qm indicates log connectivity 
```
podman exec  control bash -c "systemctl status bluechi-controller"
● bluechi-controller.service - BlueChi Controller systemd service
     Loaded: loaded (/usr/lib/systemd/system/bluechi-controller.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-06-14 14:12:45 UTC; 1h 40min ago

Jun 14 15:52:16 control bluechi-controller[158]: Node 'qm-node1' disconnected
Jun 14 15:52:45 control bluechi-controller[158]: Registered managed node from fd 11 as 'qm-node1'

```

While the following 
```
podman exec node1 bash -c "systemctl status bluechi-agent"
● bluechi-agent.service - BlueChi systemd service controller agent daemon
     Loaded: loaded (/usr/lib/systemd/system/bluechi-agent.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-06-14 14:14:00 UTC; 1h 40min ago


Jun 14 14:14:00 node1 systemd[1]: Started BlueChi systemd service controller agent daemon.
Jun 14 14:14:00 node1 bluechi-agent[1960]: Starting bluechi-agent 0.9.0-0.202405230627.git23191d3
Jun 14 14:14:00 node1 bluechi-agent[1960]: Connecting to controller on tcp:host=10.90.0.2,port=842
Jun 14 14:14:00 node1 bluechi-agent[1960]: Connected to controller as 'node1'
````

More tests here, it seems that network is down every 60-90 seconds
Install in node1
`dnf -y install --releasever 9 --installroot /usr/lib/qm/rootfs python iputils` 

ControllerHost=10.90.0.2

[root@node1 ~]# podman exec qm bash -c "ping  10.90.0.2"
```
bash-5.1# ping  10.90.0.2
PING 10.90.0.2 (10.90.0.2) 56(84) bytes of data.
64 bytes from 10.90.0.2: icmp_seq=1 ttl=63 time=0.255 ms
64 bytes from 10.90.0.2: icmp_seq=14 ttl=63 time=0.213 ms
**64 bytes from 10.90.0.2: icmp_seq=48 ttl=63 time=2368 ms
64 bytes from 10.90.0.2: icmp_seq=49 ttl=63 time=1344 ms**
64 bytes from 10.90.0.2: icmp_seq=50 ttl=63 time=320 ms
64 bytes from 10.90.0.2: icmp_seq=51 ttl=63 time=0.282 ms
64 bytes from 10.90.0.2: icmp_seq=52 ttl=63 time=0.136 ms
64 bytes from 10.90.0.2: icmp_seq=53 ttl=63 time=0.135 ms
64 bytes from 10.90.0.2: icmp_seq=54 ttl=63 time=0.216 ms
```

It also happens from the namespace itself 
```
[root@node1 ~]# ip netns exec netns-f7133da7-ba6f-4ba2-f366-ad80f5835436 ping 10.90.0.2
PING 10.90.0.2 (10.90.0.2) 56(84) bytes of data.
```

While ping from node1 to controller adress is not uninterruptible

### LINKED ISSUE #473: Modify qm quadlet file should be done through drop-in systemd files
This commented out part should be deleted

https://github.com/containers/qm/pull/472
Once adding doc for tests, "how to update qm quadlet file"

Assume one would like to expose port inside qm network
cat /etc/containers/systemd/qm.container.d/10-openport.conf  
[Container]
ExposeHostPort=842

Once running /usr/lib/systemd/system-generators/podman-system-generator --dryrun
the output should indicate reading qm quadlet updates from drop-in dir

```
quadlet-generator[4450]: Loading source unit file /usr/share/containers/systemd/qm.container
quadlet-generator[4450]: Loading source drop-in file /etc/containers/systemd/qm.container.d/10-openport.conf
```
systemd drop-in files are enabled in podman5

### PR DESCRIPTION
**Pull request by Yarboa**
TZ update to sync tier-0 testing

remove containers host containers from disk on cleanup
Remove qm.service update referencing to usage of drop-in files
    
fixes #451, fixes #462, fixes  #473

Signed-off-by: Yariv Rachmani <yrachman@redhat.com>

### CODE REVIEW

File: tests/ffi/memory/test.sh [hunk 1]
```diff
@@ -29,3 +28,4 @@ if [ $? -eq 137 ]; then
     echo ffi-qm was killed by SIGKILL
 fi
 exec_cmd "systemctl status qm --no-pager | grep \"qm.service: A process of this unit has been killed\""
+
```
Comment (dougsland) [inline tests/ffi/memory/test.sh:31]: no need empty space.

File: tests/ffi/common/prepare.sh [hunk 2]
```diff
@@ -2,33 +2,31 @@
...
-   exec_cmd "restorecon -RFv /var/lib/containers"
-   # Create qm container custom config folder
-   exec_cmd "mkdir -p /etc/containers/systemd/qm.container.d"
-   # FIXME: This action should be performed if necessary through systemd drop-in files.
-   #
-   # # Changing QM score to 1000 to avoid full memory error on SoC
-   # if [[ -n "${PACKIT_COPR_PROJECT}" && "${PACKIT_COPR_PROJECT}" == "release" ]]; then
-   #   exec_cmd "sed -i 's|OOMScoreAdjust.*|OOMScoreAdjust=1000|' ${qm_service_file}"
-   # fi
+   # Search variables for upsate file in qm.container
```
Comment (dougsland) [inline tests/ffi/common/prepare.sh:10]: update?

File: tests/ffi/disk/test.sh [hunk 3]
```diff
@@ -7,12 +7,14 @@
 disk_cleanup
 prepare_test
 
-cat << EOF > /etc/containers/systemd/qm.container.d/oom.conf
+cat << EOF > "${DROP_IN_DIR}"/oom.conf
 [Service]
+OOMScoreAdjust=
```
Comment (dougsland) [inline tests/ffi/disk/test.sh:12]: Could you please explain in a comment why we need an extra empty OOMScoreAdjust= ? Just to add a context, in few months I am sure we will forget about this. :(

**Review by dougsland — COMMENTED** [review]
lgtm, nit comments.

File: tests/ffi/disk/test.sh (hunk 3 above)
Comment (Yarboa) [reply tests/ffi/disk/test.sh:12]: Please refer this tests 
https://github.com/containers/podman/pull/20828/files#diff-320329f5ebb72bf59974a939a83d011595d510cc79f869f1e60eccb80520ab7b

Comment (dougsland) [reply tests/ffi/disk/test.sh:12]: Could you please add a comment (short) explaining it?
